version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.6

  pre_build:
    commands:
      - pwd
      - ls -la
      - terraform --version
      - terraform init

  build:
    commands:
      - terraform plan -input=false
