version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.6

  pre_build:
    commands:
      - echo "Changing directory to Root Module"
      - cd "Root Module"
      - terraform --version
      - terraform init

  build:
    commands:
      - terraform plan 

  post_build:
    commands:
      - echo "Terraform plan completed"
